export const categoryOptions = [
    "All",
    'Acne and Skin Care',
    'Alcohol',
    'Art',
    'Baby and Maternity',
    'Blockchain and Cryptocurrency',
    'Books and Fiction',
    'Business and Career',
    'Cameras, Photography and Videography',
    'Cars and Vehicles',
    'Cooking and Recipes',
    'Crafts and DIY',
    'Diet and Weight Loss',
    'Digital Marketing and Making Money Online',
    'Exercise and Fitness',
    'Farming',
    'Gardening and Lawn Care',
    'Health',
    'Makeup and Beauty',
    'Martial Arts',
    'Music and Instruments',
    'Outdoors and Hiking',
    'Pets and Animal Care',
    'Sports',
    'Technology and Gadgets',
    'Travel',
    'Wedding',
];
export const locationOptions = [
    "All",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua & Deps",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo { Democratic Rep }",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea - Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland { Republic }",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar, { Burma }",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "St Kitts & Nevis",
    "St Lucia",
    "Saint Vincent & the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];
export const followersFromOptions = [
    "All",
    "1K",
    "5K",
    "10K",
    "25K",
    "50K",
    "100K",
    "250K",
    "500K",
    "1M",
    "5M",
    "10M +"
];
export const followersToOptions = [
    "All",
    "5K",
    "10K",
    "25K",
    "50K",
    "100K",
    "250K",
    "500K",
    "1M",
    "5M",
    "10M +"
];
export const ageOptions = [
    "All",
    "Under 18",
    "18 - 24",
    "25 - 29",
    "30 - 34",
    "35 - 39",
    "40 - 44",
    "45 - 49",
    "50 - 54",
    "55 - 59",
    "60 - 64",
    "65 and Over"

];
export const genderOptions = [
    "All",
    "Male",
    "Female"
];
export const languageOptions = [
    "All",
    "English",
    "Spanish",
    "French",
    "German",
    "Chinese(Simplified)",
    "Chinese(Traditional)",
    "Japanese",
    "Korean",
    "Arabic",
    "Russian",
    "Portuguese",
    "Italian",
    "Dutch",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Greek",
    "Hebrew",
    "Hindi",
    "Turkish",
    "Polish",
    "Romanian",
    "Czech",
    "Hungarian",
    "Thai",
    "Vietnamese",
    "Indonesian",
    "Malay",
    "Swahili",
    "Urdu",
    "Bengali",
    "Tamil",
    "Tagalog",
    "Kannada",
    "Mandarin",
    "Cantonese",

];
export const engagementOptions = [
    "All",
    "< 1 %",
    "1 % - 3.5 %",
    "3.5 % - 6 %",
    "> 6 %"
];
export const ttengagementOptions = [
    "All",
    "< 7 %",
    "7 % - 12 %",
    "12 % - 17 %",
    "> 18 %"

];
export const ytengagementOptions = [
    "All",
    "< 0.5 %",
    "0.5 % - 3 %",
    "3 % - 5 %",
    "> 5 %"
];
export const twengagementOptions = [
    "All",
    "< 0.5 %",
    "0.5 % - 0.75 %",
    "0.75 % - 1.25 %",
    "> 1.25 %"
];
export const ptengagementOptions = [
    "All",
    "< 0.5 %",
    "0.5 % - 0.75 %",
    "0.75 % - 1.25 %",
    "> 1.25 %"
];
export const avglikesOptions = [
    "All",
    "< 1 %",
    "1 % - 2 %",
    "2 % - 3 %",
    "> 3 %"
];
export const avgcommentsOptions = [
    "All",
    "< 0.5 %",
    "0.5 % - 1 %",
    "1 % - 2 %",
    "> 2 %"
];
export const avgViewsOptions = [
    "All",
    "< 50 %",
    "50 % - 60 %",
    "60 % - 70 %",
    "> 70 %"

];
export const avgDislikesOptions = [
    "All",
    "< 1 %",
    "1 % - 2 %",
    "2 % - 3 %",
    "> 3 %"
];
export const connectionsOptions = [
    "All",
    "< 500",
    "500 - 750",
    "750 - 1000",
    "> 1000"

];
export const industryOptions = [
    "All",
    "Information Technology and Services",
    "Banking and Finance",
    "Healthcare and Medical",
    "Education",
    "Marketing and Advertising",
    "Manufacturing",
    "Retail",
    "Real Estate",
    "Construction",
    "Government and Administration",
    "Telecommunications",
    "Automotive",
    "Hospitality",
    "Nonprofit and Social Services",
    "Legal Services",
    "Media and Entertainment",
    "Energy and Utilities",
    "Environmental Services",
    "Transportation and Logistics",
    "Consumer Goods",
    "Pharmaceuticals",
    "Aerospace and Defense",
    "Food and Beverage",
    "Human Resources",
    "Research"
];
export const skillsOptions = [
    "All",
    "Leadership",
    "Communication",
    "Project Management",
    "Microsoft Office(e.g., Excel, Word, PowerPoint)",
    "Teamwork",
    "Customer Service",
    "Time Management",
    "Problem - Solving",
    "Data Analysis",
    "Microsoft Excel",
    "Social Media Marketing",
    "Sales",
    "Digital Marketing",
    "Public Speaking",
    "Marketing Strategy",
    "Business Development",
    "Negotiation",
    "Product Management",
    "Analytics",
    "Content Marketing",
    "Strategic Planning",
    "Team Leadership",
    "Financial Analysis",
    "SQL(Structured Query Language)",
    "Adobe Creative Suite(e.g., Photoshop, Illustrator, InDesign)"
];
export const totalfavoritesOptions = [
    "",
    "3K-8K"
];
export const totallikesOptions = [
    "",
    "3K-8K"
];